### ISSUE TITLE
upyun-uss-script/migrate_file_between_buckets/transfer_file.py 文件有bug

### ISSUE THREAD

**Issue by oudemen** [upyun/upyun-uss-script#5]
你好：
      
        迁移脚本upyun-uss-script/migrate_file_between_buckets/transfer_file.py有问题
        第124行缩进错误：
        push_tasks(new_path, up) 应该与if同级
        第19行：
        参数notify_url，不能为空。否则回报异常。建议增加修改默认值比如空格，或者增加说明

**Comment by binbinah** [comment]
> 你好：
> 
> ```
>     迁移脚本upyun-uss-script/migrate_file_between_buckets/transfer_file.py有问题
>     第124行缩进错误：
>     push_tasks(new_path, up) 应该与if同级
>     第19行：
>     参数notify_url，不能为空。否则回报异常。建议增加修改默认值比如空格，或者增加说明
> ```

非常感谢，已经在 https://github.com/upyun/upyun-uss-script/commit/dd1c539447325c79285a85d05cad84be7d41c5e1 修复
